# Generated by Django 2.1.7 on 2019-02-22 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feb_id', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=80)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feb_id', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=80)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feb_id', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=80)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feb_id', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=80)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('feb_id', models.CharField(blank=True, max_length=10, null=True)),
                ('city', models.CharField(blank=True, max_length=80, null=True)),
                ('color', models.CharField(blank=True, max_length=20, null=True)),
                ('color2', models.CharField(blank=True, max_length=20, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='basket_scraper.Category')),
                ('competition', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='basket_scraper.Competition')),
            ],
        ),
        migrations.CreateModel(
            name='TeamPhase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matches_played', models.IntegerField()),
                ('matches_won', models.IntegerField()),
                ('matches_lost', models.IntegerField()),
                ('position', models.IntegerField()),
                ('points_for', models.IntegerField()),
                ('points_against', models.IntegerField()),
                ('points_total', models.IntegerField()),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='basket_scraper.Group')),
                ('phase', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='basket_scraper.Phase')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='basket_scraper.Team')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='teamphase',
            unique_together={('team', 'group')},
        ),
        migrations.AlterUniqueTogether(
            name='team',
            unique_together={('name', 'category')},
        ),
    ]
